### ISSUE TITLE
Closing clients

### ISSUE THREAD

**Issue by billyrudi** [tiagordc/node-red-contrib-tcp-client#3]
Hi, tanks for replay.
are you sure that the function
var close = function() {
if (connectionPool[id]) {
var socket = connectionPool[id];
socket.end();
socket.destroy();
socket.unref();
server.close();
delete connectionPool[id];
}
};

is rigth? server.close(); ??

If hi make several  connections and i use close functions all connections are closed!

**Comment by tiagordc** [comment]
makes sense, will look into this

**Comment by tiagordc** [comment]
I'll create another node to have a server behavior. This one will be just client (due to the name) connecting to a server or waiting for connections on a specific port. 

It would be too complex to configure different behaviors for client / server

**Comment by tiagordc** [comment]
Moving that code to https://github.com/tiagordc/node-red-contrib-tcp-server
