### ISSUE TITLE
connection pool id

### ISSUE THREAD

**Issue by billyrudi** [tiagordc/node-red-contrib-tcp-client#4]
hi,
in your code connection pool is 
 var id = node.port.toString(16);
but i think taht it must by a rundom number assigned the first time to each connection
like
 var id = (1+Math.random()*4294967295).toString(16);
if not there is not difference between clients!
and store it in 
 msg._session = {type:"tcp",id:id};

**Comment by tiagordc** [comment]
Same as #3
